package command;

public enum CommandType {
    HELP, INFO, SHOW, INSERT, UPDATE, REMOVE_KEY, CLEAR, EXIT, REMOVE_GREATER, REMOVE_GREATER_KEY, FILTER_CONTAINS_DESCRIPTION, FILTER_GREATER_THAN_AGE, PRINT_UNIQUE_COLOR, PORT
}
